# theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

title: ChallengeMe
description: Test-based, Open-Source code learning platform.


# # theme documentation: https://pmarsceill.github.io/just-the-docs/docs/configuration/
# logo: "/photos/CM_Single_Blue.svg"

aux_links:
  "see ChallengeMe Online":
    - "//http://35.239.15.221:8080/"

# # Makes Aux links open in a new tab. Default is false
# aux_links_new_tab: false

back_to_top: true
back_to_top_text: "Go back up"

# # Color scheme supports "light" (default) and "dark"
# color_scheme: dark

# # Define Jekyll collections
# collections:
#   # Define a collection named "API", its documents reside in the "_API" directory
#   API:
#     permalink: "/:collection/:path/"
#     output: true
#   Guides:
#     permalink: "/:collection/:path/"
#     output: true

# ChallengeME:
#   # Define which collections are used in just-the-docs
#   collections:
#     # Reference the "API" collection
#     API:
#       # Give the collection a name
#       name: API Reference
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       nav_exclude: false
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       search_exclude: false
#     Guides:
#       name: Guides