# This is a basic workflow to help you get started with Actions

name: CI-SERVER

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [master,staging] # if github changes the 'master' to 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.17
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: challenge_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node  (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Server dependencies
        run: npm ci
        working-directory: ./server
      - name: create and migrate DB, then test
        run: |
          npm run initDB &&
          npm run migrate &&
          npm run test
        env:
          NODE_ENV: "test"
          DB_TEST: "challenge_test"
          IP_ADDRESS: "http://localhost:3000"
          RESET_PASSWORD_TOKEN: "dslkfrjr894utjeriiofj2389ey378wegsdyr8gf578th45igojkldfmvsf934rj490je"
          ACCESS_TOKEN_SECRET: "sdlkmf4930fjerfdfokvmdsldm1920ejeiockdv950gij54eorjflrf9430r4rjo34plre"
          EMAIL_TOKEN_SECRET: "dsvldfmldkm54y89j5effdc389ejewkmcsldmf4390rfwemdpvmdlfkg509gker0krkf94f"
          REFRESH_TOKEN_SECRET: "dfgklfmg834t3958tjervr9fft4ejrfknf32893rufjriofj5905t4i5t905itreokf5822"
          WEBHOOK_SECRET: "sdfkjndfsdjfnskjfnsdfjkn345456756764n3rwkjednn34kn5t5kjtgrndfjknvsjkenr43jnt5"
          SUVELOCITY_MAIL: suvelocity@gmail.com
        working-directory: ./server
